// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

//! Port of `Ratpack` (`ratpak.h`): the infinite precision rational package.
//!
//! The C++ `NUMBER` struct (`sign`, `cdigit`, `exp`, `mant[]`) is represented
//! by [`crate::Number`], with `cdigit == mant.len()`. A `RAT` (`pp`/`pq`) is
//! [`Rat`]. The C++ functions that take `PNUMBER*`/`PRAT*` out-parameters
//! take `&mut` here, and everything that can `throw` returns [`CalcResult`].
//!
//! The process globals of ratpak (`g_ratio`, `g_ftrueinfinite`, the decimal
//! separator, `cbitsofprecision` and every `num_*`/`rat_*` constant) live in
//! the single [`Ctx`] struct, held in a thread-local and passed down
//! explicitly as `&Ctx`.
//!
//! Integer arithmetic on exponents, digit counts and precisions uses
//! two's-complement wrapping where the C++ could overflow (MSVC wraps; the
//! differential oracle is compiled with `-fwrapv`).

pub(crate) mod basex;
pub(crate) mod conv;
pub(crate) mod exp;
pub(crate) mod fact;
pub(crate) mod itrans;
pub(crate) mod itransh;
pub(crate) mod logic;
pub(crate) mod num;
pub(crate) mod rat;
#[rustfmt::skip] // generated by tools/gen_ratconst.py
pub(crate) mod ratconst;
pub(crate) mod support;
pub(crate) mod trans;
pub(crate) mod transh;

use std::cell::RefCell;

pub(crate) use crate::{CalcResult, Number};

/// Internal log2(BASEX)
pub(crate) const BASEXPWR: u32 = 31;
/// Internal radix used in calculations.
pub(crate) const BASEX: u32 = 0x8000_0000;
/// Base 2 requires 32 'digits'
pub(crate) const MAX_LONG_SIZE: u32 = 33;

/// `RAT`: `pp / pq`, where `pp` and `pq` are integral `NUMBER`s.
#[derive(Clone, Debug)]
pub(crate) struct Rat {
    pub pp: Number,
    pub pq: Number,
}

impl Number {
    /// `cdigit`
    #[inline]
    pub(crate) fn cdigit(&self) -> i32 {
        self.mant.len() as i32
    }

    /// `mant[0]`. C++ reads `mant[0]` unconditionally even when
    /// `cdigit == 0`; the slot is always a calloc'd zero in that case.
    #[inline]
    pub(crate) fn d0(&self) -> u32 {
        self.mant.first().copied().unwrap_or(0)
    }

    /// `MSD(x)`: `mant[cdigit - 1]`.
    #[inline]
    pub(crate) fn msd(&self) -> u32 {
        self.mant.last().copied().unwrap_or(0)
    }
}

// ---------------------------------------------------------------------------
// Macros from ratpak.h
// ---------------------------------------------------------------------------

/// `LOGNUMRADIX(pnum)`
#[inline]
pub(crate) fn lognumradix(ctx: &Ctx, pnum: &Number) -> i32 {
    pnum.cdigit()
        .wrapping_add(pnum.exp)
        .wrapping_mul(ctx.g_ratio)
}

/// `LOGRATRADIX(prat)`
#[inline]
pub(crate) fn logratradix(ctx: &Ctx, prat: &Rat) -> i32 {
    lognumradix(ctx, &prat.pp).wrapping_sub(lognumradix(ctx, &prat.pq))
}

/// `LOGNUM2(pnum)`
#[inline]
pub(crate) fn lognum2(pnum: &Number) -> i32 {
    pnum.cdigit().wrapping_add(pnum.exp)
}

/// `LOGRAT2(prat)`
#[inline]
pub(crate) fn lograt2(prat: &Rat) -> i32 {
    lognum2(&prat.pp).wrapping_sub(lognum2(&prat.pq))
}

/// `SIGN(prat)`
#[inline]
pub(crate) fn sign(prat: &Rat) -> i32 {
    prat.pp.sign.wrapping_mul(prat.pq.sign)
}

/// `ABSRAT(x)`
#[inline]
pub(crate) fn absrat(x: &mut Rat) {
    x.pp.sign = 1;
    x.pq.sign = 1;
}

/// `RENORMALIZE(x)`, gets the exponents non-negative.
#[inline]
pub(crate) fn renormalize(x: &mut Rat) {
    if x.pp.exp < 0 {
        x.pq.exp = x.pq.exp.wrapping_sub(x.pp.exp);
        x.pp.exp = 0;
    }
    if x.pq.exp < 0 {
        x.pp.exp = x.pp.exp.wrapping_sub(x.pq.exp);
        x.pq.exp = 0;
    }
}

/// Drops the `trim` least significant digits (the `memmove` in the TRIM
/// macros). Clamped so a malformed input cannot index out of bounds where the
/// C++ would read out of bounds.
#[inline]
pub(crate) fn drop_low_digits(x: &mut Number, trim: usize) {
    let trim = trim.min(x.mant.len());
    x.mant.drain(..trim);
}

/// `TRIMNUM(x, precision)`. ASSUMES the number is in radix form NOT INTERNAL BASEX!!!
#[inline]
pub(crate) fn trimnum(ctx: &Ctx, x: &mut Number, precision: i32) {
    if !ctx.g_ftrueinfinite {
        let trim = x.cdigit().wrapping_sub(precision).wrapping_sub(ctx.g_ratio);
        if trim > 1 {
            drop_low_digits(x, trim as usize);
            x.exp = x.exp.wrapping_add(trim);
        }
    }
}

/// `TRIMTOP(x, precision)`. ASSUMES the number is in INTERNAL BASEX!!!
#[inline]
pub(crate) fn trimtop(ctx: &Ctx, x: &mut Rat, precision: i32) {
    if !ctx.g_ftrueinfinite {
        let mut trim =
            x.pp.cdigit()
                .wrapping_sub(precision / ctx.g_ratio)
                .wrapping_sub(2);
        if trim > 1 {
            drop_low_digits(&mut x.pp, trim as usize);
            x.pp.exp = x.pp.exp.wrapping_add(trim);
        }
        trim = x.pp.exp.min(x.pq.exp);
        x.pp.exp = x.pp.exp.wrapping_sub(trim);
        x.pq.exp = x.pq.exp.wrapping_sub(trim);
    }
}

/// `SMALL_ENOUGH_RAT(a, precision)`
#[inline]
pub(crate) fn small_enough_rat(ctx: &Ctx, a: &Rat, precision: i32) -> bool {
    num::zernum(&a.pp)
        || (a.pq.cdigit().wrapping_add(a.pq.exp))
            .wrapping_sub(a.pp.cdigit().wrapping_add(a.pp.exp))
            .wrapping_sub(1)
            .wrapping_mul(ctx.g_ratio)
            > precision
}

/// `INC(a)`: the rational equivalent of `a++`.
#[inline]
pub(crate) fn inc(ctx: &Ctx, a: &mut Number) -> CalcResult<()> {
    if a.d0() < BASEX - 1 {
        a.mant[0] += 1;
        Ok(())
    } else {
        num::addnum(a, &ctx.num_one, BASEX)
    }
}

/// `CREATETAYLOR()` minus the `thisterm`/`n2` declarations: returns
/// `(xx, pret)` where `xx = x*x` and `pret = 0/0`.
pub(crate) fn create_taylor(ctx: &Ctx, px: &Rat, precision: i32) -> CalcResult<(Rat, Rat)> {
    let mut xx = px.clone();
    rat::mulrat(ctx, &mut xx, px, precision)?;
    Ok((xx, zero_over_zero()))
}

/// The `pret` set up by `CREATETAYLOR()`: `i32tonum(0)/i32tonum(0)`.
pub(crate) fn zero_over_zero() -> Rat {
    Rat {
        pp: conv::i32tonum(0, BASEX),
        pq: conv::i32tonum(0, BASEX),
    }
}

/// `DESTROYTAYLOR()`: `trimit(&pret); *px = pret`.
pub(crate) fn destroy_taylor(ctx: &Ctx, px: &mut Rat, mut pret: Rat, precision: i32) {
    support::trimit(ctx, &mut pret, precision);
    *px = pret;
}

// ---------------------------------------------------------------------------
// Global state
// ---------------------------------------------------------------------------

/// Every process global of ratpak, in one place.
#[derive(Clone, Debug)]
pub(crate) struct Ctx {
    /// `g_ratio`: int(log(2L^BASEXPWR)/log(radix))
    pub g_ratio: i32,
    /// `g_ftrueinfinite`
    pub g_ftrueinfinite: bool,
    /// `g_decimalSeparator`
    pub decimal_separator: char,
    /// `cbitsofprecision` (support.cpp file static)
    pub cbitsofprecision: i32,

    pub num_one: Number,
    pub num_two: Number,
    pub num_five: Number,
    pub num_six: Number,
    pub num_ten: Number,

    pub ln_ten: Rat,
    pub ln_two: Rat,
    pub rat_zero: Rat,
    pub rat_neg_one: Rat,
    pub rat_one: Rat,
    pub rat_two: Rat,
    pub rat_six: Rat,
    pub rat_half: Rat,
    pub rat_ten: Rat,
    pub pt_eight_five: Rat,
    pub pi: Rat,
    pub pi_over_two: Rat,
    pub two_pi: Rat,
    pub one_pt_five_pi: Rat,
    pub e_to_one_half: Rat,
    pub rat_exp: Rat,
    pub rad_to_deg: Rat,
    pub rad_to_grad: Rat,
    pub rat_qword: Rat,
    pub rat_dword: Rat,
    pub rat_word: Rat,
    pub rat_byte: Rat,
    pub rat_360: Rat,
    pub rat_400: Rat,
    pub rat_180: Rat,
    pub rat_200: Rat,
    pub rat_nradix: Rat,
    pub rat_smallest: Rat,
    pub rat_negsmallest: Rat,
    pub rat_max_exp: Rat,
    pub rat_min_exp: Rat,
    pub rat_max_fact: Rat,
    pub rat_min_fact: Rat,
    pub rat_max_i32: Rat,
    pub rat_min_i32: Rat,
}

thread_local! {
    static CTX: RefCell<Ctx> = RefCell::new(Ctx::initial());
}

/// Runs `f` with shared access to this thread's ratpak globals.
pub(crate) fn with_ctx<R>(f: impl FnOnce(&Ctx) -> R) -> R {
    CTX.with(|c| f(&c.borrow()))
}

/// Runs `f` with exclusive access to this thread's ratpak globals.
pub(crate) fn with_ctx_mut<R>(f: impl FnOnce(&mut Ctx) -> R) -> R {
    CTX.with(|c| f(&mut c.borrow_mut()))
}
