// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
//
// GENERATED by crates/ratpack/tools/gen_ratconst.py from Ratpack/ratconst.h.
// DO NOT EDIT BY HAND.
// 73 arrays, 183 digits in total.

//! Precomputed ratpack constants (radix 10, precision 32), read by
//! `_readconstants` in `ChangeConstants`.

/// Raw `NUMBER` initialiser, as dumped by `_dumprawnum`.
#[derive(Clone, Copy, Debug)]
pub(crate) struct RawNumber {
    pub sign: i32,
    pub cdigit: i32,
    pub exp: i32,
    pub mant: &'static [u32],
}

pub(crate) const RATCONST_ARRAY_COUNT: usize = 73;
#[allow(dead_code)]
pub(crate) const RATCONST_DIGIT_COUNT: usize = 183;

pub(crate) const INIT_NUM_ONE: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_NUM_TWO: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[2],
};
pub(crate) const INIT_NUM_FIVE: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[5],
};
pub(crate) const INIT_NUM_SIX: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[6],
};
pub(crate) const INIT_NUM_TEN: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[10],
};
pub(crate) const INIT_P_RAT_SMALLEST: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_Q_RAT_SMALLEST: RawNumber = RawNumber {
    sign: 1,
    cdigit: 4,
    exp: 0,
    mant: &[0, 190439170, 901055854, 10097],
};
pub(crate) const INIT_P_RAT_NEGSMALLEST: RawNumber = RawNumber {
    sign: -1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_Q_RAT_NEGSMALLEST: RawNumber = RawNumber {
    sign: 1,
    cdigit: 4,
    exp: 0,
    mant: &[0, 190439170, 901055854, 10097],
};
pub(crate) const INIT_P_PT_EIGHT_FIVE: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[85],
};
pub(crate) const INIT_Q_PT_EIGHT_FIVE: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[100],
};
pub(crate) const INIT_P_RAT_SIX: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[6],
};
pub(crate) const INIT_Q_RAT_SIX: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_P_RAT_TWO: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[2],
};
pub(crate) const INIT_Q_RAT_TWO: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_P_RAT_ZERO: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[0],
};
pub(crate) const INIT_Q_RAT_ZERO: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_P_RAT_ONE: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_Q_RAT_ONE: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_P_RAT_NEG_ONE: RawNumber = RawNumber {
    sign: -1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_Q_RAT_NEG_ONE: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_P_RAT_HALF: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_Q_RAT_HALF: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[2],
};
pub(crate) const INIT_P_RAT_TEN: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[10],
};
pub(crate) const INIT_Q_RAT_TEN: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_P_PI: RawNumber = RawNumber {
    sign: 1,
    cdigit: 6,
    exp: 0,
    mant: &[
        125527896,
        283898350,
        1960493936,
        1672850762,
        1288168272,
        8,
    ],
};
pub(crate) const INIT_Q_PI: RawNumber = RawNumber {
    sign: 1,
    cdigit: 6,
    exp: 0,
    mant: &[
        1288380402,
        1120116153,
        1860424692,
        1944118326,
        1583591604,
        2,
    ],
};
pub(crate) const INIT_P_TWO_PI: RawNumber = RawNumber {
    sign: 1,
    cdigit: 6,
    exp: 0,
    mant: &[
        251055792,
        567796700,
        1773504224,
        1198217877,
        428852897,
        17,
    ],
};
pub(crate) const INIT_Q_TWO_PI: RawNumber = RawNumber {
    sign: 1,
    cdigit: 6,
    exp: 0,
    mant: &[
        1288380402,
        1120116153,
        1860424692,
        1944118326,
        1583591604,
        2,
    ],
};
pub(crate) const INIT_P_PI_OVER_TWO: RawNumber = RawNumber {
    sign: 1,
    cdigit: 6,
    exp: 0,
    mant: &[
        125527896,
        283898350,
        1960493936,
        1672850762,
        1288168272,
        8,
    ],
};
pub(crate) const INIT_Q_PI_OVER_TWO: RawNumber = RawNumber {
    sign: 1,
    cdigit: 6,
    exp: 0,
    mant: &[
        429277156,
        92748659,
        1573365737,
        1740753005,
        1019699561,
        5,
    ],
};
pub(crate) const INIT_P_ONE_PT_FIVE_PI: RawNumber = RawNumber {
    sign: 1,
    cdigit: 6,
    exp: 0,
    mant: &[
        1241201312,
        270061909,
        1051574664,
        1924965045,
        1340320627,
        70,
    ],
};
pub(crate) const INIT_Q_ONE_PT_FIVE_PI: RawNumber = RawNumber {
    sign: 1,
    cdigit: 6,
    exp: 0,
    mant: &[
        1579671539,
        1837970263,
        1067644340,
        523549916,
        2119366659,
        14,
    ],
};
pub(crate) const INIT_P_E_TO_ONE_HALF: RawNumber = RawNumber {
    sign: 1,
    cdigit: 6,
    exp: 0,
    mant: &[
        256945612,
        216219427,
        223516738,
        477442596,
        581063757,
        23,
    ],
};
pub(crate) const INIT_Q_E_TO_ONE_HALF: RawNumber = RawNumber {
    sign: 1,
    cdigit: 6,
    exp: 0,
    mant: &[
        1536828363,
        698484484,
        1127331835,
        224219346,
        245499408,
        14,
    ],
};
pub(crate) const INIT_P_RAT_EXP: RawNumber = RawNumber {
    sign: 1,
    cdigit: 6,
    exp: 0,
    mant: &[
        943665199,
        1606559160,
        1094967530,
        1759391384,
        1671799163,
        1123581,
    ],
};
pub(crate) const INIT_Q_RAT_EXP: RawNumber = RawNumber {
    sign: 1,
    cdigit: 6,
    exp: 0,
    mant: &[
        879242208,
        2022880100,
        617392930,
        1374929092,
        1367479163,
        413342,
    ],
};
pub(crate) const INIT_P_LN_TEN: RawNumber = RawNumber {
    sign: 1,
    cdigit: 6,
    exp: 0,
    mant: &[
        2086268922,
        165794492,
        1416063951,
        1851428830,
        1893239400,
        65366841,
    ],
};
pub(crate) const INIT_Q_LN_TEN: RawNumber = RawNumber {
    sign: 1,
    cdigit: 6,
    exp: 0,
    mant: &[
        26790652,
        564532679,
        783998273,
        216030448,
        1564709968,
        28388458,
    ],
};
pub(crate) const INIT_P_LN_TWO: RawNumber = RawNumber {
    sign: 1,
    cdigit: 6,
    exp: 0,
    mant: &[
        1789230241,
        1057927868,
        715399197,
        908801241,
        1411265331,
        3,
    ],
};
pub(crate) const INIT_Q_LN_TWO: RawNumber = RawNumber {
    sign: 1,
    cdigit: 6,
    exp: 0,
    mant: &[
        1559869847,
        1930657510,
        1228561531,
        219003871,
        593099283,
        5,
    ],
};
pub(crate) const INIT_P_RAD_TO_DEG: RawNumber = RawNumber {
    sign: 1,
    cdigit: 6,
    exp: 0,
    mant: &[
        2127722024,
        1904928383,
        2016479213,
        2048947859,
        1578647346,
        492,
    ],
};
pub(crate) const INIT_Q_RAD_TO_DEG: RawNumber = RawNumber {
    sign: 1,
    cdigit: 6,
    exp: 0,
    mant: &[
        125527896,
        283898350,
        1960493936,
        1672850762,
        1288168272,
        8,
    ],
};
pub(crate) const INIT_P_RAD_TO_GRAD: RawNumber = RawNumber {
    sign: 1,
    cdigit: 6,
    exp: 0,
    mant: &[
        2125526288,
        684931327,
        570267400,
        129125085,
        1038224725,
        547,
    ],
};
pub(crate) const INIT_Q_RAD_TO_GRAD: RawNumber = RawNumber {
    sign: 1,
    cdigit: 6,
    exp: 0,
    mant: &[
        125527896,
        283898350,
        1960493936,
        1672850762,
        1288168272,
        8,
    ],
};
pub(crate) const INIT_P_RAT_QWORD: RawNumber = RawNumber {
    sign: 1,
    cdigit: 3,
    exp: 0,
    mant: &[2147483647, 2147483647, 3],
};
pub(crate) const INIT_Q_RAT_QWORD: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_P_RAT_DWORD: RawNumber = RawNumber {
    sign: 1,
    cdigit: 2,
    exp: 0,
    mant: &[2147483647, 1],
};
pub(crate) const INIT_Q_RAT_DWORD: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_P_RAT_MAX_I32: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[2147483647],
};
pub(crate) const INIT_Q_RAT_MAX_I32: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_P_RAT_MIN_I32: RawNumber = RawNumber {
    sign: -1,
    cdigit: 2,
    exp: 0,
    mant: &[0, 1],
};
pub(crate) const INIT_Q_RAT_MIN_I32: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_P_RAT_WORD: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[65535],
};
pub(crate) const INIT_Q_RAT_WORD: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_P_RAT_BYTE: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[255],
};
pub(crate) const INIT_Q_RAT_BYTE: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_P_RAT_400: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[400],
};
pub(crate) const INIT_Q_RAT_400: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_P_RAT_360: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[360],
};
pub(crate) const INIT_Q_RAT_360: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_P_RAT_200: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[200],
};
pub(crate) const INIT_Q_RAT_200: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_P_RAT_180: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[180],
};
pub(crate) const INIT_Q_RAT_180: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_P_RAT_MAX_EXP: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[100000],
};
pub(crate) const INIT_Q_RAT_MAX_EXP: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_P_RAT_MIN_EXP: RawNumber = RawNumber {
    sign: -1,
    cdigit: 1,
    exp: 0,
    mant: &[100000],
};
pub(crate) const INIT_Q_RAT_MIN_EXP: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_P_RAT_MAX_FACT: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[3249],
};
pub(crate) const INIT_Q_RAT_MAX_FACT: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};
pub(crate) const INIT_P_RAT_MIN_FACT: RawNumber = RawNumber {
    sign: -1,
    cdigit: 1,
    exp: 0,
    mant: &[1000],
};
pub(crate) const INIT_Q_RAT_MIN_FACT: RawNumber = RawNumber {
    sign: 1,
    cdigit: 1,
    exp: 0,
    mant: &[1],
};

/// Every constant, in file order (used to check the generated output).
#[allow(dead_code)]
pub(crate) const ALL: [(&str, RawNumber); RATCONST_ARRAY_COUNT] = [
    ("init_num_one", INIT_NUM_ONE),
    ("init_num_two", INIT_NUM_TWO),
    ("init_num_five", INIT_NUM_FIVE),
    ("init_num_six", INIT_NUM_SIX),
    ("init_num_ten", INIT_NUM_TEN),
    ("init_p_rat_smallest", INIT_P_RAT_SMALLEST),
    ("init_q_rat_smallest", INIT_Q_RAT_SMALLEST),
    ("init_p_rat_negsmallest", INIT_P_RAT_NEGSMALLEST),
    ("init_q_rat_negsmallest", INIT_Q_RAT_NEGSMALLEST),
    ("init_p_pt_eight_five", INIT_P_PT_EIGHT_FIVE),
    ("init_q_pt_eight_five", INIT_Q_PT_EIGHT_FIVE),
    ("init_p_rat_six", INIT_P_RAT_SIX),
    ("init_q_rat_six", INIT_Q_RAT_SIX),
    ("init_p_rat_two", INIT_P_RAT_TWO),
    ("init_q_rat_two", INIT_Q_RAT_TWO),
    ("init_p_rat_zero", INIT_P_RAT_ZERO),
    ("init_q_rat_zero", INIT_Q_RAT_ZERO),
    ("init_p_rat_one", INIT_P_RAT_ONE),
    ("init_q_rat_one", INIT_Q_RAT_ONE),
    ("init_p_rat_neg_one", INIT_P_RAT_NEG_ONE),
    ("init_q_rat_neg_one", INIT_Q_RAT_NEG_ONE),
    ("init_p_rat_half", INIT_P_RAT_HALF),
    ("init_q_rat_half", INIT_Q_RAT_HALF),
    ("init_p_rat_ten", INIT_P_RAT_TEN),
    ("init_q_rat_ten", INIT_Q_RAT_TEN),
    ("init_p_pi", INIT_P_PI),
    ("init_q_pi", INIT_Q_PI),
    ("init_p_two_pi", INIT_P_TWO_PI),
    ("init_q_two_pi", INIT_Q_TWO_PI),
    ("init_p_pi_over_two", INIT_P_PI_OVER_TWO),
    ("init_q_pi_over_two", INIT_Q_PI_OVER_TWO),
    ("init_p_one_pt_five_pi", INIT_P_ONE_PT_FIVE_PI),
    ("init_q_one_pt_five_pi", INIT_Q_ONE_PT_FIVE_PI),
    ("init_p_e_to_one_half", INIT_P_E_TO_ONE_HALF),
    ("init_q_e_to_one_half", INIT_Q_E_TO_ONE_HALF),
    ("init_p_rat_exp", INIT_P_RAT_EXP),
    ("init_q_rat_exp", INIT_Q_RAT_EXP),
    ("init_p_ln_ten", INIT_P_LN_TEN),
    ("init_q_ln_ten", INIT_Q_LN_TEN),
    ("init_p_ln_two", INIT_P_LN_TWO),
    ("init_q_ln_two", INIT_Q_LN_TWO),
    ("init_p_rad_to_deg", INIT_P_RAD_TO_DEG),
    ("init_q_rad_to_deg", INIT_Q_RAD_TO_DEG),
    ("init_p_rad_to_grad", INIT_P_RAD_TO_GRAD),
    ("init_q_rad_to_grad", INIT_Q_RAD_TO_GRAD),
    ("init_p_rat_qword", INIT_P_RAT_QWORD),
    ("init_q_rat_qword", INIT_Q_RAT_QWORD),
    ("init_p_rat_dword", INIT_P_RAT_DWORD),
    ("init_q_rat_dword", INIT_Q_RAT_DWORD),
    ("init_p_rat_max_i32", INIT_P_RAT_MAX_I32),
    ("init_q_rat_max_i32", INIT_Q_RAT_MAX_I32),
    ("init_p_rat_min_i32", INIT_P_RAT_MIN_I32),
    ("init_q_rat_min_i32", INIT_Q_RAT_MIN_I32),
    ("init_p_rat_word", INIT_P_RAT_WORD),
    ("init_q_rat_word", INIT_Q_RAT_WORD),
    ("init_p_rat_byte", INIT_P_RAT_BYTE),
    ("init_q_rat_byte", INIT_Q_RAT_BYTE),
    ("init_p_rat_400", INIT_P_RAT_400),
    ("init_q_rat_400", INIT_Q_RAT_400),
    ("init_p_rat_360", INIT_P_RAT_360),
    ("init_q_rat_360", INIT_Q_RAT_360),
    ("init_p_rat_200", INIT_P_RAT_200),
    ("init_q_rat_200", INIT_Q_RAT_200),
    ("init_p_rat_180", INIT_P_RAT_180),
    ("init_q_rat_180", INIT_Q_RAT_180),
    ("init_p_rat_max_exp", INIT_P_RAT_MAX_EXP),
    ("init_q_rat_max_exp", INIT_Q_RAT_MAX_EXP),
    ("init_p_rat_min_exp", INIT_P_RAT_MIN_EXP),
    ("init_q_rat_min_exp", INIT_Q_RAT_MIN_EXP),
    ("init_p_rat_max_fact", INIT_P_RAT_MAX_FACT),
    ("init_q_rat_max_fact", INIT_Q_RAT_MAX_FACT),
    ("init_p_rat_min_fact", INIT_P_RAT_MIN_FACT),
    ("init_q_rat_min_fact", INIT_Q_RAT_MIN_FACT),
];
