#!/usr/bin/env python3
"""Write THIRD-PARTY-LICENSES.txt from cargo-about's JSON (see generate.sh)."""

import json
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HERE = ROOT / "packaging/licences"

# Code kept in this repository rather than taken from crates.io.
VENDORED = [
    (
        "CORE-MATH: correctly rounded maths functions, used by Graphing",
        ["crates/crmath/vendor/COPYRIGHT", "crates/crmath/vendor/LICENSE"],
    ),
    (
        "smithay-clipboard: DGMNB's Wayland clipboard code is adapted from it",
        ["apps/dgmnb/assets/LICENSE-smithay-clipboard.txt"],
    ),
]

# Crates published without licence files (cargo-about falls back to a
# template), with their notices in supplements/ and the versions those were
# checked against. Any other such crate, or a new version, stops the script
# until a supplement is written or checked again.
SUPPLEMENTS = {
    "accesskit.txt": {
        "accesskit": "0.25.1",
        "accesskit_atspi_common": "0.21.0",
        "accesskit_consumer": "0.39.1",
        "accesskit_unix": "0.24.0",
        "accesskit_winit": "0.34.1",
    },
}

# Licence files cargo-about doesn't pick up, reproduced whole: ring's
# LICENSE points at LICENSE-BoringSSL, which also carries notices for
# BoringSSL's support code.
EXTRA_FILES = {"ring": ["LICENSE", "LICENSE-BoringSSL"]}

RULE = "-" * 72
HEADER = """\
Third-party licences
====================

GMNB, DGMNB and gmnb-launcher are MIT licensed (LICENSE). They also contain
code by others, under the licences below: first the code kept in this
repository, then the Rust crates the programs are built from. The crates are
the dependency graph of all three programs together, at the versions in
Cargo.lock; each program contains a subset, and the procedural-macro crates
only run while building. The fonts' licences (SIL Open Font License 1.1) are
separate files.

Generated by packaging/licences/generate.sh, with cargo-about; don't edit.
"""


def clean(text):
    lines = text.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    return "\n".join(line.rstrip() for line in lines).strip("\n") + "\n"


def used_by(crates):
    return textwrap.fill(
        ", ".join(sorted(crates)),
        72,
        initial_indent="Used by: ",
        subsequent_indent="  ",
        break_on_hyphens=False,
        break_long_words=False,
    )


def section(title, body):
    return f"{RULE}\n{title}\n\n{clean(body)}"


def main():
    data = json.load(open(sys.argv[1]))
    pkgs = {
        c["package"]["name"]: c["package"]
        for c in data["crates"]
        if c["package"]["source"]
    }
    groups, fallback = {}, {}
    for lic in data["licenses"]:
        users = [u["crate"] for u in lic["used_by"] if u["crate"]["source"]]
        if not users:
            continue  # this repository's own crates
        if not lic.get("source_path"):
            fallback.update((u["name"], u["version"]) for u in users)
            continue
        # The same licence, wrapped or indented differently, is one group.
        g = groups.setdefault(
            " ".join(lic["text"].split()),
            {"name": lic["name"], "id": lic["id"], "text": lic["text"], "crates": set()},
        )
        g["crates"].update(f"{u['name']} {u['version']}" for u in users)

    errors = []
    checked = {n: (f, v) for f, cs in SUPPLEMENTS.items() for n, v in cs.items()}
    for name, version in sorted(fallback.items()):
        if name not in checked:
            errors.append(f"{name} {version}: no licence file; add a supplement")
        elif checked[name][1] != version:
            errors.append(
                f"{name} is now {version}: recheck supplements/{checked[name][0]}"
            )
    for name in sorted(checked.keys() - fallback.keys()):
        errors.append(f"{name}: no longer needs supplements/{checked[name][0]}")
    for name in sorted(EXTRA_FILES.keys() - pkgs.keys()):
        errors.append(f"{name}: no longer a dependency; drop it from EXTRA_FILES")
    if not any(g["id"] == "Apache-2.0" for g in groups.values()):
        errors.append("supplements/accesskit.txt refers to an Apache-2.0 text")
    if errors:
        sys.exit("render.py: " + "\n  ".join(errors))

    out = [HEADER, "\n" + "=" * 72 + "\nCode kept in this repository\n" + "=" * 72 + "\n"]
    for title, files in VENDORED:
        out.append(section(title, "\n".join((ROOT / f).read_text() for f in files)))
    out.append("\n" + "=" * 72 + "\nRust crates\n" + "=" * 72 + "\n")
    for g in sorted(groups.values(), key=lambda g: (g["id"], min(g["crates"]))):
        out.append(section(f"{g['name']}\n{used_by(g['crates'])}", g["text"]))
    for name, files in EXTRA_FILES.items():
        pkg = pkgs[name]
        src = Path(pkg["manifest_path"]).parent
        body = "\n".join(f"{f}:\n\n{clean((src / f).read_text())}" for f in files)
        title = f"{name} {pkg['version']}: its {' and '.join(files)} files, whole"
        out.append(section(title, body))
    for f, crates in SUPPLEMENTS.items():
        names = [f"{n} {v}" for n, v in crates.items()]
        out.append(section(used_by(names), (HERE / "supplements" / f).read_text()))
    sys.stdout.write("\n".join(out))


main()
