#!/usr/bin/env python3
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
#
# Mechanically converts Ratpack/ratconst.h (the C initialisers produced by
# `_dumprawrat` in support.cpp) into Rust constants.
#
# Usage (from the workspace root):
#   python3 crates/ratpack/tools/gen_ratconst.py \
#       reference/calculator/src/CalcManager/Ratpack/ratconst.h \
#       crates/ratpack/src/ratpak/ratconst.rs
#
# The script verifies that every array's digit count matches its `cdigit`
# field and that the expected number of arrays (73) was found.

import re
import sys

EXPECTED_ARRAYS = 73

ENTRY_RE = re.compile(
    r"inline\s+const\s+NUMBER\s+(\w+)\s*=\s*\{\s*"
    r"(-?\d+)\s*,\s*"  # sign
    r"(-?\d+)\s*,\s*"  # cdigit
    r"(-?\d+)\s*,\s*"  # exp
    r"\{([^}]*)\}\s*\}\s*;",
    re.S,
)


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__ or "usage: gen_ratconst.py <ratconst.h> <out.rs>", file=sys.stderr)
        return 2
    src_path, out_path = sys.argv[1], sys.argv[2]
    with open(src_path, "r", encoding="utf-8-sig") as f:  # utf-8-sig strips the BOM
        text = f.read()

    entries = []
    for m in ENTRY_RE.finditer(text):
        name, sign, cdigit, exp, body = m.groups()
        digits = [d.strip() for d in body.split(",") if d.strip()]
        for d in digits:
            if not re.fullmatch(r"\d+", d):
                raise SystemExit(f"{name}: unexpected digit token {d!r}")
            if int(d) >= 2**31:
                raise SystemExit(f"{name}: digit {d} not < BASEX")
        if len(digits) != int(cdigit):
            raise SystemExit(f"{name}: cdigit={cdigit} but {len(digits)} digits listed")
        entries.append((name, int(sign), int(cdigit), int(exp), digits))

    # Every `inline const NUMBER` declaration must have been parsed.
    decls = len(re.findall(r"inline\s+const\s+NUMBER", text))
    if decls != len(entries):
        raise SystemExit(f"parsed {len(entries)} of {decls} declarations")
    if len(entries) != EXPECTED_ARRAYS:
        raise SystemExit(f"expected {EXPECTED_ARRAYS} arrays, found {len(entries)}")

    total_digits = sum(e[2] for e in entries)
    out = []
    out.append("// Copyright (c) Microsoft Corporation. All rights reserved.")
    out.append("// Licensed under the MIT License.")
    out.append("//")
    out.append("// GENERATED by crates/ratpack/tools/gen_ratconst.py from Ratpack/ratconst.h.")
    out.append("// DO NOT EDIT BY HAND.")
    out.append(f"// {len(entries)} arrays, {total_digits} digits in total.")
    out.append("")
    out.append("//! Precomputed ratpack constants (radix 10, precision 32), read by")
    out.append("//! `_readconstants` in `ChangeConstants`.")
    out.append("")
    out.append("/// Raw `NUMBER` initialiser, as dumped by `_dumprawnum`.")
    out.append("#[derive(Clone, Copy, Debug)]")
    out.append("pub(crate) struct RawNumber {")
    out.append("    pub sign: i32,")
    out.append("    pub cdigit: i32,")
    out.append("    pub exp: i32,")
    out.append("    pub mant: &'static [u32],")
    out.append("}")
    out.append("")
    out.append(f"pub(crate) const RATCONST_ARRAY_COUNT: usize = {len(entries)};")
    out.append("#[allow(dead_code)]")
    out.append(f"pub(crate) const RATCONST_DIGIT_COUNT: usize = {total_digits};")
    out.append("")
    for name, sign, cdigit, exp, digits in entries:
        const_name = name.upper()
        out.append(f"pub(crate) const {const_name}: RawNumber = RawNumber {{")
        out.append(f"    sign: {sign},")
        out.append(f"    cdigit: {cdigit},")
        out.append(f"    exp: {exp},")
        if len(digits) <= 4:
            out.append(f"    mant: &[{', '.join(digits)}],")
        else:
            out.append("    mant: &[")
            for d in digits:
                out.append(f"        {d},")
            out.append("    ],")
        out.append("};")
    out.append("")
    out.append("/// Every constant, in file order (used to check the generated output).")
    out.append("#[allow(dead_code)]")
    out.append("pub(crate) const ALL: [(&str, RawNumber); RATCONST_ARRAY_COUNT] = [")
    for name, *_ in entries:
        out.append(f"    (\"{name}\", {name.upper()}),")
    out.append("];")
    out.append("")

    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print(f"wrote {out_path}: {len(entries)} arrays, {total_digits} digits")
    return 0


if __name__ == "__main__":
    sys.exit(main())
